### ISSUE TITLE
Connection to http://repo.opensourceagility.com refused

### ISSUE THREAD

**Issue by dreamdust** [michaellavelle/spring-social-hibernate-jpa#1]
Hello,

Recently I encountered an issue with connection to your maven repo. I got the error message:

[WARNING] Could not transfer metadata org.springframework.social:jpa:0.0.1-SNAPS
HOT/maven-metadata.xml from/to opensourceagility-snapshots (http://repo.opensour
ceagility.com/snapshots): Connection to http://repo.opensourceagility.com refuse
d

[WARNING] Failure to transfer org.springframework.social:jpa:0.0.1-SNAPSHOT/mave
n-metadata.xml from http://repo.opensourceagility.com/snapshots was cached in th
e local repository, resolution will not be reattempted until the update interval
 of opensourceagility-snapshots has elapsed or updates are forced. Original erro
r: Could not transfer metadata org.springframework.social:jpa:0.0.1-SNAPSHOT/mav
en-metadata.xml from/to opensourceagility-snapshots (http://repo.opensourceagili
ty.com/snapshots): Connection to http://repo.opensourceagility.com refused

I was wondering what happened and how I can resolve this issue.

Thanks,

**Comment by michaellavelle** [comment]
Hi - thanks for letting me know about this. It looks like there was an issue with Apache which serves the repo - this should be resolved now, but please do let me know if you encounter any more issues.   Many thanks, Michael

**Comment by dreamdust** [comment]
It works now. Thank you Michael.
